// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *PlainTxDAG) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, _tmp2 := range obj.TxDeps {
		_tmp3 := w.List()
		_tmp4 := w.List()
		for _, _tmp5 := range _tmp2.TxIndexes {
			w.WriteUint64(_tmp5)
		}
		w.ListEnd(_tmp4)
		_tmp6 := _tmp2.Flags != nil
		if _tmp6 {
			if _tmp2.Flags == nil {
				w.Write([]byte{0x80})
			} else {
				w.WriteUint64(uint64((*_tmp2.Flags)))
			}
		}
		w.ListEnd(_tmp3)
	}
	w.ListEnd(_tmp1)
	w.ListEnd(_tmp0)
	return w.Flush()
}
